import type { Country } from "./types"

export const sampleCountries: Omit<Country, "_id">[] = [
  {
    name: "United States",
    code: "US",
    image: "/placeholder.svg?height=300&width=400",
    description: "Experience the land of opportunities with diverse landscapes and vibrant cities.",
    visaCategories: [
      {
        id: "us-tourist",
        name: "Tourist Visa (B-2)",
        type: "Tourist",
        price: 15000,
        processingTime: "15-30 days",
        validity: "Up to 10 years",
        entries: "Multiple",
        requiredDocuments: [
          "Valid Passport (minimum 6 months validity)",
          "Passport Size Photos (2 pieces, 51mm x 51mm)",
          "DS-160 Form (completed online)",
          "Bank Statements (last 6 months)",
          "Employment Letter with salary details",
          "Travel Itinerary",
          "Hotel Bookings",
          "Income Tax Returns (last 3 years)",
        ],
        processSteps: [
          "Fill DS-160 form online at ceac.state.gov",
          "Pay visa application fee ($185)",
          "Schedule visa interview appointment",
          "Gather all required documents",
          "Attend visa interview at US Consulate",
          "Submit biometric information",
          "Wait for visa processing",
          "Collect passport with visa stamp",
        ],
        eligibility: [
          "Purpose of travel is tourism/vacation",
          "Sufficient funds to cover expenses",
          "Strong ties to home country",
          "No intention to immigrate",
        ],
        additionalInfo: "B-2 visa allows tourism, visiting family/friends, and medical treatment.",
      },
      {
        id: "us-business",
        name: "Business Visa (B-1)",
        type: "Business",
        price: 18000,
        processingTime: "15-30 days",
        validity: "Up to 10 years",
        entries: "Multiple",
        requiredDocuments: [
          "Valid Passport (minimum 6 months validity)",
          "DS-160 Form (completed online)",
          "Business invitation letter from US company",
          "Company registration documents",
          "Bank Statements (last 6 months)",
          "Employment Letter",
          "Business license",
          "Conference/meeting details",
        ],
        processSteps: [
          "Receive invitation from US business partner",
          "Fill DS-160 form online",
          "Pay visa application fee",
          "Schedule interview appointment",
          "Prepare business documentation",
          "Attend visa interview",
          "Submit biometric information",
          "Collect passport with visa",
        ],
        eligibility: [
          "Legitimate business purpose",
          "Invitation from US company",
          "Sufficient business ties",
          "No intention to work in US",
        ],
        additionalInfo: "B-1 visa for business meetings, conferences, and negotiations.",
      },
    ],
  },
  {
    name: "United Kingdom",
    code: "GB",
    image: "/placeholder.svg?height=300&width=400",
    description: "Explore the rich history and culture of England, Scotland, Wales, and Northern Ireland.",
    visaCategories: [
      {
        id: "uk-tourist",
        name: "Standard Visitor Visa",
        type: "Tourist",
        price: 12000,
        processingTime: "15-20 days",
        validity: "6 months",
        entries: "Multiple",
        requiredDocuments: [
          "Valid Passport",
          "Passport Size Photos",
          "Bank Statements (last 6 months)",
          "Employment Letter",
          "Travel Itinerary",
          "Accommodation Proof",
          "Travel Insurance",
          "Sponsor Documents (if applicable)",
        ],
        processSteps: [
          "Apply online at gov.uk",
          "Pay visa application fee",
          "Book biometric appointment",
          "Attend biometric appointment",
          "Submit supporting documents",
          "Wait for decision",
          "Collect passport",
        ],
        eligibility: [
          "Tourism or visiting family/friends",
          "Sufficient funds for stay",
          "Genuine intention to leave UK",
          "No public funds required",
        ],
        additionalInfo: "Standard Visitor visa for tourism and family visits.",
      },
    ],
  },
  {
    name: "Canada",
    code: "CA",
    image: "/placeholder.svg?height=300&width=400",
    description: "Discover the natural beauty and multicultural cities of Canada.",
    visaCategories: [
      {
        id: "ca-tourist",
        name: "Temporary Resident Visa",
        type: "Tourist",
        price: 8000,
        processingTime: "20-30 days",
        validity: "Up to 10 years",
        entries: "Multiple",
        requiredDocuments: [
          "Valid Passport",
          "Passport Size Photos",
          "Bank Statements",
          "Employment Letter",
          "Travel Itinerary",
          "Purpose of Visit Letter",
          "Invitation Letter (if applicable)",
          "Travel Insurance",
        ],
        processSteps: [
          "Apply online or on paper",
          "Pay application fees",
          "Submit biometrics",
          "Submit supporting documents",
          "Wait for processing",
          "Receive passport with visa",
        ],
        eligibility: ["Temporary visit purpose", "Sufficient funds", "No criminal record", "Good health"],
        additionalInfo: "Temporary Resident Visa for tourism and business visits.",
      },
    ],
  },
  {
    name: "Australia",
    code: "AU",
    image: "/placeholder.svg?height=300&width=400",
    description: "Experience the unique wildlife and stunning landscapes of Australia.",
    visaCategories: [
      {
        id: "au-tourist",
        name: "Visitor Visa (Subclass 600)",
        type: "Tourist",
        price: 10000,
        processingTime: "15-25 days",
        validity: "12 months",
        entries: "Multiple",
        requiredDocuments: [
          "Valid Passport",
          "Passport Size Photos",
          "Bank Statements",
          "Employment Letter",
          "Travel Insurance",
          "Health Insurance",
          "Character Documents",
          "Travel Itinerary",
        ],
        processSteps: [
          "Apply online via ImmiAccount",
          "Pay application fee",
          "Submit documents",
          "Health examination (if required)",
          "Wait for decision",
          "Receive visa grant notification",
        ],
        eligibility: [
          "Tourism or business visitor",
          "Sufficient funds",
          "Health requirements met",
          "Character requirements met",
        ],
        additionalInfo: "Visitor visa for tourism and short business visits.",
      },
    ],
  },
  {
    name: "Germany",
    code: "DE",
    image: "/placeholder.svg?height=300&width=400",
    description: "Explore the heart of Europe with its rich history and modern cities.",
    visaCategories: [
      {
        id: "de-tourist",
        name: "Schengen Tourist Visa",
        type: "Tourist",
        price: 7000,
        processingTime: "10-15 days",
        validity: "90 days",
        entries: "Multiple",
        requiredDocuments: [
          "Valid Passport",
          "Passport Size Photos",
          "Travel Insurance (minimum €30,000)",
          "Bank Statements",
          "Flight Reservations",
          "Hotel Bookings",
          "Employment Certificate",
          "Cover Letter",
        ],
        processSteps: [
          "Book appointment at German Consulate",
          "Fill Schengen visa application form",
          "Gather required documents",
          "Attend appointment",
          "Submit biometrics and documents",
          "Pay visa fee",
          "Collect passport",
        ],
        eligibility: [
          "Tourism purpose",
          "Sufficient financial means",
          "Valid travel insurance",
          "Return ticket booked",
        ],
        additionalInfo: "Schengen visa valid for 26 European countries.",
      },
    ],
  },
  {
    name: "Japan",
    code: "JP",
    image: "/placeholder.svg?height=300&width=400",
    description: "Experience the perfect blend of traditional culture and modern technology.",
    visaCategories: [
      {
        id: "jp-tourist",
        name: "Tourist Visa",
        type: "Tourist",
        price: 6000,
        processingTime: "5-10 days",
        validity: "90 days",
        entries: "Single",
        requiredDocuments: [
          "Valid Passport",
          "Passport Size Photos",
          "Visa Application Form",
          "Bank Statements",
          "Travel Itinerary",
          "Employment Certificate",
          "Hotel Reservations",
          "Return Flight Tickets",
        ],
        processSteps: [
          "Fill visa application form",
          "Gather required documents",
          "Submit at Japanese Consulate",
          "Pay visa fee",
          "Wait for processing",
          "Collect passport with visa",
        ],
        eligibility: ["Tourism purpose only", "Sufficient funds", "Return ticket confirmed", "No work intention"],
        additionalInfo: "Tourist visa for short-term visits up to 90 days.",
      },
    ],
  },
]
