import type { Country } from "./types"

export const sampleCountries: Omit<Country, "_id">[] = [
  {
    name: "United States",
    code: "US",
    image: "/placeholder.svg?height=300&width=400",
    description: "Experience the land of opportunities with diverse landscapes and vibrant cities.",
    visa: {
      type: "B1-B2",
      price: 15000,
      processingTime: "15-30 days",
      requiredDocuments: [
        "Valid Passport (minimum 6 months validity)",
        "Passport Size Photos (2 pieces, 51mm x 51mm)",
        "DS-160 Form (completed online)",
        "Bank Statements (last 6 months)",
        "Employment Letter with salary details",
        "Travel Itinerary",
        "Hotel Bookings or Invitation Letter",
        "Income Tax Returns (last 3 years)",
        "Property Documents (if applicable)",
        "Family Ties Documents",
      ],
      processSteps: [
        "Fill DS-160 form online at ceac.state.gov",
        "Pay visa application fee ($185)",
        "Schedule visa interview appointment",
        "Gather all required documents",
        "Attend visa interview at US Consulate",
        "Submit biometric information",
        "Wait for visa processing",
        "Collect passport with visa stamp",
      ],
      additionalInfo:
        "B1-B2 visa allows both business and tourism activities. Valid for up to 10 years with multiple entries.",
    },
  },
  {
    name: "United Kingdom",
    code: "GB",
    image: "/placeholder.svg?height=300&width=400",
    description: "Explore the rich history and culture of England, Scotland, Wales, and Northern Ireland.",
    visa: {
      type: "B1-B2",
      price: 12000,
      processingTime: "15-20 days",
      requiredDocuments: [
        "Valid Passport",
        "Passport Size Photos",
        "Bank Statements (last 6 months)",
        "Employment Letter",
        "Travel Itinerary",
        "Accommodation Proof",
        "Travel Insurance",
        "Sponsor Documents (if applicable)",
      ],
      processSteps: [
        "Apply online at gov.uk",
        "Pay visa application fee",
        "Book biometric appointment",
        "Attend biometric appointment",
        "Submit supporting documents",
        "Wait for decision",
        "Collect passport",
      ],
      additionalInfo: "Standard Visitor visa for business and tourism purposes.",
    },
  },
  {
    name: "Canada",
    code: "CA",
    image: "/placeholder.svg?height=300&width=400",
    description: "Discover the natural beauty and multicultural cities of Canada.",
    visa: {
      type: "B1-B2",
      price: 8000,
      processingTime: "20-30 days",
      requiredDocuments: [
        "Valid Passport",
        "Passport Size Photos",
        "Bank Statements",
        "Employment Letter",
        "Travel Itinerary",
        "Purpose of Visit Letter",
        "Invitation Letter (if applicable)",
        "Travel Insurance",
      ],
      processSteps: [
        "Apply online or on paper",
        "Pay application fees",
        "Submit biometrics",
        "Submit supporting documents",
        "Wait for processing",
        "Receive passport with visa",
      ],
      additionalInfo: "Temporary Resident Visa for business and tourism.",
    },
  },
  {
    name: "Australia",
    code: "AU",
    image: "/placeholder.svg?height=300&width=400",
    description: "Experience the unique wildlife and stunning landscapes of Australia.",
    visa: {
      type: "B1-B2",
      price: 10000,
      processingTime: "15-25 days",
      requiredDocuments: [
        "Valid Passport",
        "Passport Size Photos",
        "Bank Statements",
        "Employment Letter",
        "Travel Insurance",
        "Health Insurance",
        "Character Documents",
        "Travel Itinerary",
      ],
      processSteps: [
        "Apply online via ImmiAccount",
        "Pay application fee",
        "Submit documents",
        "Health examination (if required)",
        "Wait for decision",
        "Receive visa grant notification",
      ],
      additionalInfo: "Visitor visa (subclass 600) for business and tourism.",
    },
  },
  {
    name: "Germany",
    code: "DE",
    image: "/placeholder.svg?height=300&width=400",
    description: "Explore the heart of Europe with its rich history and modern cities.",
    visa: {
      type: "B1-B2",
      price: 7000,
      processingTime: "10-15 days",
      requiredDocuments: [
        "Valid Passport",
        "Passport Size Photos",
        "Travel Insurance (minimum €30,000)",
        "Bank Statements",
        "Flight Reservations",
        "Hotel Bookings",
        "Employment Certificate",
        "Cover Letter",
      ],
      processSteps: [
        "Book appointment at German Consulate",
        "Fill Schengen visa application form",
        "Gather required documents",
        "Attend appointment",
        "Submit biometrics and documents",
        "Pay visa fee",
        "Collect passport",
      ],
      additionalInfo: "Schengen visa valid for 25 European countries.",
    },
  },
  {
    name: "Japan",
    code: "JP",
    image: "/placeholder.svg?height=300&width=400",
    description: "Experience the perfect blend of traditional culture and modern technology.",
    visa: {
      type: "B1-B2",
      price: 6000,
      processingTime: "5-10 days",
      requiredDocuments: [
        "Valid Passport",
        "Passport Size Photos",
        "Visa Application Form",
        "Bank Statements",
        "Travel Itinerary",
        "Employment Certificate",
        "Hotel Reservations",
        "Return Flight Tickets",
      ],
      processSteps: [
        "Fill visa application form",
        "Gather required documents",
        "Submit at Japanese Consulate",
        "Pay visa fee",
        "Wait for processing",
        "Collect passport with visa",
      ],
      additionalInfo: "Tourist visa for short-term visits up to 90 days.",
    },
  },
]
